name: Check Commit Messages

on:
  push:
    branches:
      - main  # Adjust to your default branch or any branches you want to target
      - feature
jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all commits
        run: |
          # Fetch all commits for the push event
          git fetch --prune --unshallow

      - name: Get commit messages
        id: get-commits
        run: |
          # Get commit messages for all commits in the push event
          git log --format=%B --no-merges > commit-messages.txt

      - name: Check commit messages for JIRA task IDs
        id: check-commits
        run: |
          # Define the JIRA task ID pattern
          PATTERN="^[A-Za-z]+-[0-9]+"

          # Read commit messages
          COMMIT_MESSAGES=$(cat commit-messages.txt)

          # Check each commit message for the JIRA task ID pattern
          if echo "$COMMIT_MESSAGES" | grep -P "$PATTERN"; then
            echo "All commit messages contain a valid JIRA task ID."
          else
            echo "One or more commit messages do not contain a valid JIRA task ID."
            exit 1
          fi
