name: Check GPG Signatures

on:
  pull_request:
    branches:
      - main

jobs:
  check-gpg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check GPG signatures
      run: |
        # Get the range of commits
        COMMITS=$(git log --format=%H --no-merges ${GITHUB_SHA}^..${GITHUB_SHA})

        # Check each commit for GPG signatures
        for COMMIT in $COMMITS; do
          SIGNATURE=$(git log --show-signature -1 $COMMIT | grep 'gpg')
          if [ -z "$SIGNATURE" ]; then
            echo "Error: Commit $COMMIT is not signed with GPG."
            exit 1
          else
            echo "Commit $COMMIT is signed with GPG."
          fi
        done

        echo "All commits are signed with GPG."
