name: Verify Commit Signatures

on:
  push:
    branches:
      - '*'  # Trigger for pushes to any branch
    if: github.ref != 'refs/heads/main'  
  pull_request:
    branches:
      - main  # Trigger for PRs targeting the main branch

jobs:
  verify-signatures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch all commits
        run: |
          # Ensure we have all commits
          git fetch --prune --unshallow

      - name: Verify commit signatures
        run: |
          # Determine the range of commits based on the event type
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
            # For push events, use the range from the previous commit to the current commit
            COMMITS=$(git log --format=%H --no-merges ${{ github.event.before }}..${{ github.sha }})
          elif [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            # For pull requests, get the base and head branches
            BASE_BRANCH=${{ github.event.pull_request.base.ref }}
            HEAD_BRANCH=${{ github.event.pull_request.head.ref }}
            git fetch origin $BASE_BRANCH
            git fetch origin $HEAD_BRANCH
            COMMITS=$(git log --format=%H --no-merges origin/$BASE_BRANCH..origin/$HEAD_BRANCH)
          else
            echo "Unsupported event type: $GITHUB_EVENT_NAME"
            exit 1
          fi

          # Check each commit for GPG signatures
          for COMMIT in $COMMITS; do
            SIGNATURE=$(git log --show-signature -1 $COMMIT | grep 'gpg')
            if [ -z "$SIGNATURE" ]; then
              echo "Error: Commit $COMMIT is not signed with GPG."
              exit 1
            else
              echo "Commit $COMMIT is signed with GPG."
            fi
          done

          echo "All commits are signed with GPG."
